### PR TITLE
Fix multilingual import error in Plone 5.

### PR DESCRIPTION
**Pull request by gyst**

### CODE REVIEW

**Comment by jone** [comment]
Awesome, thanks!

**Comment by gyst** [comment]
Thanks for merging! Can I have a release, I need this for a current project and would rather not depend on a source checkout.

**Comment by jone** [comment]
@gyst I have released `ftw.inflator = 1.8.1` with this change 😉

**Comment by szakitibi** [comment]
Based on plone.app.multilingual [versions info](https://github.com/plone/plone.app.multilingual/tree/2.0.3#versions): 

> 2.x - Plone >= 4.x, < 5.0 with plone.app.contenttypes (Dexterity) and real shared content

But Plone >= 4.x does not have the ILanguage interface yet, it is added only in [Plone 5.0](https://github.com/plone/Products.CMFPlone/blob/5.0/Products/CMFPlone/interfaces/language.py)

Current import solution falls back to version 1.x even if it has 2.x with Plone 4.3.x - see https://github.com/4teamwork/ftw.inflator/pull/28/commits/786e2f81a0e8854131b97a0de1aeb64156b2928b#diff-9982ea59ed18845760077bc5630e7244L25.

Means this import produces error for Plone 4.3.x + plone.app.contenttypes + plone.app.multilingual 2.x combo.

**Pull request merged**
